site_name: Mizool Playbook

nav:
  - index.md
  - Code conventions:
    - code-conventions/general-naming.md
    - code-conventions/java.md
    - code-conventions/javascript.md
    - code-conventions/maven.md
  - Best practices:
    - best-practices/user-and-address-data.md

theme:
  name: material

  features:
    - content.code.copy
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
