site_name: Mizool Playbook
repo_name: mizool/playbook
repo_url: https://github.com/mizool/playbook
edit_uri: edit/main/docs/

nav:
  - index.md
  - Code conventions:
    - code-conventions/general-naming.md
    - code-conventions/java.md
    - code-conventions/javascript.md
    - code-conventions/sql.md
    - code-conventions/maven.md
    - code-conventions/branch-naming.md
  - Best practices:
    - best-practices/application-architecture.md
    - best-practices/user-and-address-data.md

theme:
  name: material
  custom_dir: overrides
  features:
    - content.action.view
    - content.action.edit
    - content.code.copy
    - navigation.instant
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/mizool

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
